import * as XLSX from "xlsx";
import { listAdmissionPins, type PinListItem } from "@/lib/admin-pins";
import type { PinStatus } from "@/generated/prisma/client";
import { buildCsv } from "@/lib/admin-export/csv-utils";
import { exportFilename } from "@/lib/pdf/pdf-styles";

export type PinExportFilter = "all" | PinStatus;

export type PinRevenueSummary = {
  totalPins: number;
  unusedCount: number;
  usedCount: number;
  totalAmount: number;
  unusedAmount: number;
  usedAmount: number;
  defaultUnitPrice: number;
};

export function summarizePinRevenue(
  pins: PinListItem[],
  defaultUnitPrice = 450
): PinRevenueSummary {
  let unusedAmount = 0;
  let usedAmount = 0;

  for (const pin of pins) {
    const amount = Number.parseFloat(pin.amount) || defaultUnitPrice;
    if (pin.status === "used") {
      usedAmount += amount;
    } else {
      unusedAmount += amount;
    }
  }

  const unusedCount = pins.filter((p) => p.status === "unused").length;
  const usedCount = pins.filter((p) => p.status === "used").length;

  return {
    totalPins: pins.length,
    unusedCount,
    usedCount,
    totalAmount: unusedAmount + usedAmount,
    unusedAmount,
    usedAmount,
    defaultUnitPrice,
  };
}

export async function getPinsForExport(filter: PinExportFilter = "all") {
  const pins = await listAdmissionPins();
  const filtered =
    filter === "all" ? pins : pins.filter((pin) => pin.status === filter);
  const summary = summarizePinRevenue(filtered);
  return { pins: filtered, summary, filter };
}

export function pinRowsForExport(pins: PinListItem[]) {
  return pins.map((pin) => [
    pin.receiptNumber,
    pin.pinCode,
    Number.parseFloat(pin.amount).toFixed(2),
    pin.status === "used" ? "Used" : "Unused",
    pin.generatedByName,
    pin.usedByStudentName ?? "",
    pin.usedByStudentEmail ?? "",
    pin.createdAt.slice(0, 10),
    pin.usedAt?.slice(0, 10) ?? "",
  ]);
}

export function buildPinRegisterCsv(
  pins: PinListItem[],
  summary: PinRevenueSummary,
  collegeName: string
) {
  const headerBlock = [
    `${collegeName} — Admission PIN Register`,
    `Generated,${new Date().toISOString()}`,
    "",
    "Summary,Count,Amount (SLE)",
    `Total PINs,${summary.totalPins},${summary.totalAmount.toFixed(2)}`,
    `Used PINs,${summary.usedCount},${summary.usedAmount.toFixed(2)}`,
    `Unused PINs,${summary.unusedCount},${summary.unusedAmount.toFixed(2)}`,
    "",
  ];

  const table = buildCsv(
    [
      "Receipt No.",
      "PIN Code",
      "Amount (SLE)",
      "Status",
      "Generated By",
      "Student Name",
      "Student Email",
      "Created",
      "Used Date",
    ],
    pinRowsForExport(pins)
  );

  return `${headerBlock.join("\n")}${table}`;
}

export function buildPinRegisterWorkbook(
  pins: PinListItem[],
  summary: PinRevenueSummary,
  collegeName: string
) {
  const wb = XLSX.utils.book_new();

  const summarySheet = XLSX.utils.aoa_to_sheet([
    [`${collegeName} — PIN Register`],
    ["Generated", new Date().toISOString()],
    [],
    ["Metric", "Count", "Amount (SLE)"],
    ["Total PINs", summary.totalPins, summary.totalAmount],
    ["Used PINs", summary.usedCount, summary.usedAmount],
    ["Unused PINs", summary.unusedCount, summary.unusedAmount],
  ]);
  XLSX.utils.book_append_sheet(wb, summarySheet, "Summary");

  const registerSheet = XLSX.utils.json_to_sheet(
    pins.map((pin) => ({
      "Receipt No.": pin.receiptNumber,
      "PIN Code": pin.pinCode,
      "Amount (SLE)": Number.parseFloat(pin.amount),
      Status: pin.status === "used" ? "Used" : "Unused",
      "Generated By": pin.generatedByName,
      "Student Name": pin.usedByStudentName ?? "",
      "Student Email": pin.usedByStudentEmail ?? "",
      Created: pin.createdAt.slice(0, 10),
      "Used Date": pin.usedAt?.slice(0, 10) ?? "",
    }))
  );
  XLSX.utils.book_append_sheet(wb, registerSheet, "PIN Register");

  return Buffer.from(
    XLSX.write(wb, { type: "buffer", bookType: "xlsx" }) as ArrayBuffer
  );
}

export function pinExportFilename(filter: PinExportFilter, ext: string) {
  const suffix = filter === "all" ? "all-pins" : `${filter}-pins`;
  return exportFilename(`transit-${suffix}`, ext);
}
