import {
  Document,
  Page,
  Text,
  View,
} from "@react-pdf/renderer";
import PdfDocumentHeader from "@/components/admin/pdf/PdfDocumentHeader";
import type { PinListItem } from "@/lib/admin-pins";
import type { PinRevenueSummary } from "@/lib/admin-export/pin-export";
import {
  formatPdfCurrency,
  formatPdfDate,
  pdfBaseStyles,
  PDF_COLORS,
} from "@/lib/pdf/pdf-styles";

type PinRegisterPDFDocumentProps = {
  pins: PinListItem[];
  summary: PinRevenueSummary;
  collegeName: string;
  tagline?: string;
  logoSrc?: string;
  filterLabel: string;
};

const colWidths = ["14%", "14%", "10%", "9%", "14%", "16%", "16%", "7%"];

export default function PinRegisterPDFDocument({
  pins,
  summary,
  collegeName,
  tagline,
  logoSrc,
  filterLabel,
}: PinRegisterPDFDocumentProps) {
  const headers = [
    "PIN",
    "Receipt",
    "Amount",
    "Status",
    "Generated By",
    "Student",
    "Email",
    "Created",
  ];

  return (
    <Document>
      <Page size="A4" orientation="landscape" style={pdfBaseStyles.page}>
        <PdfDocumentHeader
          collegeName={collegeName}
          tagline={tagline}
          logoSrc={logoSrc}
          title="Admission PIN Register"
          subtitle={`${filterLabel} · Generated ${formatPdfDate(new Date())}`}
        />

        <Text style={pdfBaseStyles.sectionTitle}>Financial Summary</Text>
        <View style={pdfBaseStyles.summaryBox}>
          {[
            ["Total PINs", `${summary.totalPins}`, formatPdfCurrency(summary.totalAmount)],
            ["Used PINs", `${summary.usedCount}`, formatPdfCurrency(summary.usedAmount)],
            ["Unused PINs", `${summary.unusedCount}`, formatPdfCurrency(summary.unusedAmount)],
          ].map(([label, count, amount]) => (
            <View key={String(label)} style={pdfBaseStyles.summaryRow}>
              <Text style={{ fontSize: 9, color: PDF_COLORS.muted }}>{label}</Text>
              <Text style={{ fontSize: 9, fontWeight: "bold" }}>
                {count} · {amount}
              </Text>
            </View>
          ))}
        </View>

        <Text style={pdfBaseStyles.sectionTitle}>PIN Register</Text>
        <View style={pdfBaseStyles.tableHeader}>
          {headers.map((header, index) => (
            <Text
              key={header}
              style={[pdfBaseStyles.tableHeaderCell, { width: colWidths[index] }]}
            >
              {header}
            </Text>
          ))}
        </View>

        {pins.map((pin) => (
          <View key={pin.id} style={pdfBaseStyles.tableRow} wrap={false}>
            <Text style={[pdfBaseStyles.tableCell, { width: colWidths[0], fontWeight: "bold" }]}>
              {pin.pinCode}
            </Text>
            <Text style={[pdfBaseStyles.tableCell, { width: colWidths[1] }]}>
              {pin.receiptNumber ?? "—"}
            </Text>
            <Text style={[pdfBaseStyles.tableCell, { width: colWidths[2] }]}>
              {formatPdfCurrency(pin.amount)}
            </Text>
            <Text style={[pdfBaseStyles.tableCell, { width: colWidths[3] }]}>
              {pin.status === "used" ? "Used" : "Unused"}
            </Text>
            <Text style={[pdfBaseStyles.tableCell, { width: colWidths[4] }]}>
              {pin.generatedByName}
            </Text>
            <Text style={[pdfBaseStyles.tableCell, { width: colWidths[5] }]}>
              {pin.usedByStudentName ?? "—"}
            </Text>
            <Text style={[pdfBaseStyles.tableCell, { width: colWidths[6] }]}>
              {pin.usedByStudentEmail ?? "—"}
            </Text>
            <Text style={[pdfBaseStyles.tableCell, { width: colWidths[7] }]}>
              {pin.createdAt.slice(0, 10)}
            </Text>
          </View>
        ))}

        <View style={pdfBaseStyles.footer} fixed>
          <Text style={pdfBaseStyles.footerText}>{collegeName}</Text>
          <Text
            style={pdfBaseStyles.footerText}
            render={({ pageNumber, totalPages }) =>
              `Page ${pageNumber} of ${totalPages}`
            }
          />
        </View>
      </Page>
    </Document>
  );
}
